// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77_W2vShezwCG3VF9PB32xnXZMnuQdB4',
    appId: '1:809712575972:web:401ab43d0c680a4e90d3f1',
    messagingSenderId: '809712575972',
    projectId: 'reservation-system-aa45f',
    authDomain: 'reservation-system-aa45f.firebaseapp.com',
    storageBucket: 'reservation-system-aa45f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlOsW6GyXvBe_j4kdhhznpOx76C-mQ1P0',
    appId: '1:809712575972:android:7207d90e7d65ac3f90d3f1',
    messagingSenderId: '809712575972',
    projectId: 'reservation-system-aa45f',
    storageBucket: 'reservation-system-aa45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqGt-m6HiuUWllB9VgSnyM_m364zDpBE',
    appId: '1:809712575972:ios:7b0b1637704b36bf90d3f1',
    messagingSenderId: '809712575972',
    projectId: 'reservation-system-aa45f',
    storageBucket: 'reservation-system-aa45f.firebasestorage.app',
    iosBundleId: 'com.example.reservationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTqGt-m6HiuUWllB9VgSnyM_m364zDpBE',
    appId: '1:809712575972:ios:7b0b1637704b36bf90d3f1',
    messagingSenderId: '809712575972',
    projectId: 'reservation-system-aa45f',
    storageBucket: 'reservation-system-aa45f.firebasestorage.app',
    iosBundleId: 'com.example.reservationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77_W2vShezwCG3VF9PB32xnXZMnuQdB4',
    appId: '1:809712575972:web:4048fe8d12b0c24c90d3f1',
    messagingSenderId: '809712575972',
    projectId: 'reservation-system-aa45f',
    authDomain: 'reservation-system-aa45f.firebaseapp.com',
    storageBucket: 'reservation-system-aa45f.firebasestorage.app',
  );
}
